version: '3.9'
services:
  mysqldb:
    container_name: mysql-container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s1239875
    ports:
      - '4001:3306'
